# Set the base image to Jenkins
FROM        jenkins

# File Author / Maintainer
MAINTAINER Dave O'Connor

# Expose Jenkins port 8080
EXPOSE      8080

# Run Jenkins Server
ENTRYPOINT  ["/var/jenkins_home"]
